In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
escalar = np.array(12)
print(escalar)

12


In [4]:
unidimensional_array = np.array([12,4,2,55])
print(unidimensional_array)

[12  4  2 55]


In [5]:
bidimensional_array = np.array([[[12,4,2,6],
                                [12,51,6,8],
                                [12,4,7,2]],
                                [[12,4,2,6],
                                [12,51,6,8],
                                [12,4,7,2]],
                                [[12,4,2,6],
                                [12,51,6,8],
                                [12,4,7,2]]])
print(bidimensional_array)

[[[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]

 [[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]

 [[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]]


In [8]:
zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
arange_array = np.arange(0,100,3)
print(arange_array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [18]:
linspace_array = np.linspace(0,10,20)
print(linspace_array)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:
linspace_array = np.reshape(linspace_array, (5,4))
print(linspace_array)


[[ 0.          0.52631579  1.05263158  1.57894737]
 [ 2.10526316  2.63157895  3.15789474  3.68421053]
 [ 4.21052632  4.73684211  5.26315789  5.78947368]
 [ 6.31578947  6.84210526  7.36842105  7.89473684]
 [ 8.42105263  8.94736842  9.47368421 10.        ]]


In [22]:
print(arange_array.ndim)
print(arange_array.shape)
print(arange_array.size)
print(arange_array.dtype)

1
(34,)
34
int64


In [33]:
print(arange_array[0])
print(bidimensional_array[0:5])
print(bidimensional_array[:,2])


0
[[[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]

 [[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]

 [[12  4  2  6]
  [12 51  6  8]
  [12  4  7  2]]]
[[12  4  7  2]
 [12  4  7  2]
 [12  4  7  2]]


In [41]:
operation_array_one = np.array(np.random.randint(0,99,size=(3,4)))
operation_array_two = np.array(np.random.randint(0,99,size=(3,4)))

In [43]:
sum_array = operation_array_one + operation_array_two
print(sum_array)
difference_array = operation_array_one - operation_array_two
print(difference_array)
product_array = operation_array_one * operation_array_two
print(product_array)
division_array = operation_array_one / operation_array_two
print(division_array)

[[102 154 150 107]
 [153 118 166  66]
 [ 65  91 146  87]]
[[-20  38 -16   7]
 [-29 -66  28  40]
 [-19 -77  24 -69]]
[[2501 5568 5561 2850]
 [5642 2392 6693  689]
 [ 966  588 5185  702]]
[[0.67213115 1.65517241 0.80722892 1.14      ]
 [0.68131868 0.2826087  1.4057971  4.07692308]
 [0.54761905 0.08333333 1.39344262 0.11538462]]


In [44]:
exp_array = np.exp(operation_array_one)
print(exp_array)
log_array = np.log(operation_array_one)
print(log_array)
sqrt_array = np.sqrt(operation_array_one)
print(sqrt_array)


[[6.39843494e+17 4.92345829e+41 1.25236317e+29 5.68572000e+24]
 [8.43835667e+26 1.95729609e+11 1.33833472e+42 1.04137594e+23]
 [9.74480345e+09 1.09663316e+03 8.22301271e+36 8.10308393e+03]]
[[3.71357207 4.56434819 4.20469262 4.04305127]
 [4.12713439 3.25809654 4.57471098 3.97029191]
 [3.13549422 1.94591015 4.44265126 2.19722458]]
[[6.40312424 9.79795897 8.18535277 7.54983444]
 [7.87400787 5.09901951 9.8488578  7.28010989]
 [4.79583152 2.64575131 9.21954446 3.        ]]


In [45]:
maximum_array = np.maximum(operation_array_one, operation_array_two)
print(maximum_array)
minimum_array = np.minimum(operation_array_one, operation_array_two)
print(minimum_array)

[[61 96 83 57]
 [91 92 97 53]
 [42 84 85 78]]
[[41 58 67 50]
 [62 26 69 13]
 [23  7 61  9]]


In [46]:
abs_array = np.abs(operation_array_one)
print(abs_array)

[[41 96 67 57]
 [62 26 97 53]
 [23  7 85  9]]
